apiVersion: v1
kind: Service
metadata:
  name: chatgpt
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: 'lb-l4vofgphs35w1wxwg4j6c'
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  selector:
    app: chatgpt